---
# Middleware SOA Postvalidation Playbook

- name: Check Current OPatch Version (SOA1)
  shell: echo "host:"$(hostname) >> {{PostOPatchVersion_log}};echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_SOA1;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch version >> {{PostOPatchVersion_log}}cpwcsoa_$(hostname)_opatchversion.log
  
- name: Check Current OPatch Version (SOA1)
  shell: echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_SOA1;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch version
  register: ps

- debug: var=ps.stdout_lines

- name: Check ORACLE_HOME size (SOA1)
  shell: echo $(hostname) >> {{PostORAHOMEsize_log}};echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_SOA1;du -sh $ORACLE_HOME >> {{PostORAHOMEsize_log}}cpwcsoa_$(hostname)_opatchversion.log

- name: Check ORACLE_HOME size (SOA1)
  shell: echo "host:"$(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_SOA1;du -sh $ORACLE_HOME
  register: ps

- debug: var=ps.stdout_lines

- name: Current Patch Applied (SOA1)
  shell: echo "host:"$(hostname) >> {{PostPatchApplied_log}};echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_SOA1;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch lsinventory -invPtrLoc $ORACLE_HOME/oraInst.loc >> {{PostPatchApplied_log}}cpwcsoa_$(hostname)_opatchversion.log

- name: Current Patch Applied (SOA1)
  shell: echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_SOA1;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch lsinventory -invPtrLoc $ORACLE_HOME/oraInst.loc
  register: ps
  
- debug: var=ps.stdout_lines

- name: Current Common Patch Applied (SOA1)
  shell: echo "host:"$(hostname) >> {{PostComPatchApplied_log}};echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/oracle_common;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch lsinventory |grep applied >> {{PostComPatchApplied_log}}cpwcsoa_$(hostname)_opatchversion.log

- name: Current Common Patch Applied (SOA1)
  shell: echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/oracle_common;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch lsinventory |grep applied
  register: ps

- debug: var=ps.stdout_lines