---
# dea DOMAIN DIFF
- name: Temp CommPatchApp
  shell: cat {{ComPatchApplied_tmp_log}}deapre_*_compatchapplied.tmp.log > {{ComPatchApplied_tmp_log}}deapre_compatchapplied.fnl.log;cat {{PostComPatchApplied_tmp_log}}deapost_*_compatchapplied.tmp.log > {{PostComPatchApplied_tmp_log}}deapost_compatchapplied.fnl.log
  become: true
  ignore_errors: yes  
  changed_when: false
  
- name: Temp Weblogic Version
  shell: cat {{WeblogicVersion_tmp_log}}deapre_*_weblogicversion.tmp.log > {{WeblogicVersion_tmp_log}}deapre_weblogicversion.fnl.log;cat {{PostWeblogicVersion_tmp_log}}deapost_*_weblogicversion.tmp.log > {{PostWeblogicVersion_tmp_log}}deapost_weblogicversion.fnl.log
  become: true
  ignore_errors: yes  
  changed_when: false
  
- name: Temp Mount Point
  shell: cat {{mountPoint_tmp_log}}deapre_*_mountpoint.tmp.log > {{mountPoint_tmp_log}}deapre_mountpoint.fnl.log;cat {{PostmountPoint_tmp_log}}deapost_*_mountpoint.tmp.log > {{PostmountPoint_tmp_log}}deapost_mountpoint.fnl.log
  become: true
  ignore_errors: yes  
  changed_when: false
  