---
# rtda DOMAIN DIFF
- name: Temp CommPatchApp
  shell: cat {{ComPatchApplied_tmp_log}}rtdapre_*_compatchapplied.tmp.log > {{ComPatchApplied_tmp_log}}rtdapre_compatchapplied.fnl.log;cat {{PostComPatchApplied_tmp_log}}rtdapost_*_compatchapplied.tmp.log > {{PostComPatchApplied_tmp_log}}rtdapost_compatchapplied.fnl.log
  become: true
  ignore_errors: yes  
  changed_when: false
  
- name: Temp Weblogic Version
  shell: cat {{WeblogicVersion_tmp_log}}rtdapre_*_weblogicversion.tmp.log > {{WeblogicVersion_tmp_log}}rtdapre_weblogicversion.fnl.log;cat {{PostWeblogicVersion_tmp_log}}rtdapost_*_weblogicversion.tmp.log > {{PostWeblogicVersion_tmp_log}}rtdapost_weblogicversion.fnl.log
  become: true
  ignore_errors: yes  
  changed_when: false
  
- name: Temp Mount Point
  shell: cat {{mountPoint_tmp_log}}rtdapre_*_mountpoint.tmp.log > {{mountPoint_tmp_log}}rtdapre_mountpoint.fnl.log;cat {{PostmountPoint_tmp_log}}rtdapost_*_mountpoint.tmp.log > {{PostmountPoint_tmp_log}}rtdapost_mountpoint.fnl.log
  become: true
  ignore_errors: yes  
  changed_when: false
  