---
# Middleware WCP Prevalidation Playbook
  
- name: Check Current OPatch Version (WCP)
  shell: echo "host:"$(hostname) >> {{OPatchVersion_log}};echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_WC1;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch version >> {{OPatchVersion_log}}cpwc_$(hostname)_opatchversion.log
  
- name: Check Current OPatch Version (WCP)
  shell: echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_WC1;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch version
  register: ps
  
- debug: var=ps.stdout_lines

- name: Check ORACLE_HOME size (WCP)
  shell: echo "host:"$(hostname) >> {{ORAHOMEsize_log}};echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_WC1;du -sh $ORACLE_HOME >> {{ORAHOMEsize_log}}cpwc_$(hostname)_orahomesize.log

- name: Check ORACLE_HOME size (WCP)
  shell: echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_WC1;du -sh $ORACLE_HOME
  register: ps

- debug: var=ps.stdout_lines

- name: Current Patch Applied (WCP)
  shell: echo "host:"$(hostname) >> {{PatchApplied_log}};echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_WC1;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch lsinventory -invPtrLoc $ORACLE_HOME/oraInst.loc >> {{PatchApplied_log}}cpwc_$(hostname)_patchapplied.log

- name: Current Patch Applied (WCP)
  shell: echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/Oracle_WC1;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch lsinventory -invPtrLoc $ORACLE_HOME/oraInst.loc
  register: ps
  
- debug: var=ps.stdout_lines

- name: Current Common Patch Applied (WCP)
  shell: echo "host:"$(hostname) >> {{ComPatchApplied_log}};echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/oracle_common;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch lsinventory |grep applied >> {{ComPatchApplied_log}}cpwc_$(hostname)_compatchapplied.log

- name: Current Common Patch Applied (WCP)
  shell: echo $(hostname) for $(date);export ORACLE_HOME=/app/ENP/fmw1036/oracle_common;export PATH=$PATH:$ORACLE_HOME/OPatch:$ORACLE_HOME/bin;$ORACLE_HOME/OPatch/opatch lsinventory |grep applied
  register: ps

- debug: var=ps.stdout_lines

